steps:
- name: 'node:18' # Use a Node.js image to build your React app
  entrypoint: 'npm'
  args: ['install']
- name: 'node:18'
  entrypoint: 'npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--project', '${PROJECT_ID}']
timeout: '1600s' # Adjust timeout if needed